name = ""
main = "main.jsx"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = true

rules = [
  { type = "Text", globs = ["**/*.cdc", "**/*.cdc?raw"], fallthrough = true }
]

[[durable_objects.bindings]]
name = "AGENT"
class_name = "DurableObject"

[[migrations]]
tag = "v1"
new_classes = ["DurableObject"]

[vars]
WORKER_ENV = "production"